#!/usr/bin/env bash
# shellcheck disable=SC1091
source "$(dirname "${0}")/_core.bash"

if [[ "$(uname -s)" == "Darwin" ]]; then
	>&2 echo 'No Darwin Install'
else
	>&2 echo 'No Linux Install'
fi

# vim: set ft=bash :
