# reMarkable Light — managed by color-theme
foreground            #292a28
background            #e3e1da
cursor                 #292a28
cursor_text_color      #e3e1da
selection_foreground   #292a28
selection_background   #c5c4bd

color0  #1f201e
color1  #9c3d34
color2  #377748
color3  #956600
color4  #326591
color5  #794982
color6  #006f76
color7  #686964
color8  #8a8b85
color9  #bd4034
color10 #359050
color11 #b57d00
color12 #2d7fb6
color13 #9552a2
color14 #008790
color15 #3d3e3a

active_tab_foreground   #f2f0e9
active_tab_background   #326591
active_tab_font_style   bold-italic
inactive_tab_foreground #686964
inactive_tab_background #d8d6cf
inactive_tab_font_style normal
